# Generated by Django 5.2.7 on 2025-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('performed_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('treatment', 'Treatment'), ('observation', 'Observation'), ('other', 'Other')], default='observation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('once', 'Sekali'), ('weekly', 'Mingguan'), ('monthly', 'Bulanan')], default='once', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
