# Generated by Django 5.2.7 on 2025-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('plant_part', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0.0)),
                ('checklist', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('additional_requests', models.JSONField(default=list)),
                ('follow_up_questions', models.JSONField(default=list)),
                ('consensus_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
